In [4]:
import numpy as np

# Dos listas de datos
x = [55, 56, 58, 56, 59,57,60,53,59]
y = [3,2,2,1,1,2,1,3,2]

# Calcular el coeficiente de correlación de Pearson
correlation_coefficient = np.corrcoef(x, y)[0, 1]
correlation_coefficient_matrix = np.corrcoef(x, y)
print("El coeficiente de correlación es:", correlation_coefficient)
print(correlation_coefficient_matrix)

El coeficiente de correlación es: -0.7150969419341943
[[ 1.         -0.71509694]
 [-0.71509694  1.        ]]


In [2]:
import numpy as np

# Dos listas de datos
x = [10, 20, 30, 40, 50]
y = [15, 25, 35, 45, 55]

# Calcular el coeficiente de correlación de Pearson
correlation_coefficient = np.corrcoef(x, y)

print("El coeficiente de correlación es:", correlation_coefficient)

El coeficiente de correlación es: [[1. 1.]
 [1. 1.]]


In [10]:
W = np.array([0.807,0.074])
b = -0.0742

x = [55, 56, 58, 56, 59,57,60,53,59]
y = [3,2,2,1,1,2,1,3,2]
X = np.array([[55,3],[56,2],[58,2],[56,1],[59,1],[57,2],[60,1],[53,3],[59,2]])


predict = np.dot(X,W) + b
print(predict)

[44.5328 45.2658 46.8798 45.1918 47.6128 46.0728 48.4198 42.9188 47.6868]


In [18]:
import numpy as np
from sklearn import model_selection,preprocessing

# Datos originales
W = np.array([0.0807, 0.074])
b = -0.0742

x = [55, 56, 58, 56, 59,57,60,53,59]
y = [3, 2, 2, 1, 1, 2, 1, 3, 2]
X = np.array([[55, 3], [56, 2], [58, 2], [56, 1], [59, 1], [57, 2], [60, 1], [53, 3], [59, 2]])

 #--- Normalización lineal entre 0 y 1 ---
normalizador = preprocessing.MinMaxScaler()
X = normalizador.fit_transform(X)

# Cálculo de la predicción con los datos normalizados
input = np.dot(X, W) + b
print("X normalizado:\n", X)
print(input)
prediction = np.where(input >= 0.0, 1, 0)
print(prediction)

#Valores para probar
X_entry = np.array([[50,1],[51,2],[54,3]])
input = np.dot(X_entry , W) + b
prediction_dos = np.where(input >= 0.0,1,0)
print(prediction_dos)

X normalizado:
 [[0.28571429 1.        ]
 [0.42857143 0.5       ]
 [0.71428571 0.5       ]
 [0.42857143 0.        ]
 [0.85714286 0.        ]
 [0.57142857 0.5       ]
 [1.         0.        ]
 [0.         1.        ]
 [0.85714286 0.5       ]]
[ 0.02285714 -0.00261429  0.02044286 -0.03961429 -0.00502857  0.00891429
  0.0065     -0.0002      0.03197143]
[1 0 1 0 0 1 1 0 1]
[1 1 1]
