In [7]:
import pandas as pd
import numpy as np
from matplotlib import pylab as plt

from sklearn import model_selection,preprocessing
from sklearn import  metrics
from ClassPerceptron import Perceptron

In [14]:
datos = pd.read_csv("automobile-simple.csv")

#marca --> Nominal
#combustible --> Nominal
#puertas --> discreto
#body-style --> Nominal
#Peso en vacio --> Continuo
#Engine size --> Continuo
#Horsepower --> Continuo
#Rendimiento en la ciudad --> Continuo
#Precio --> Continuo
#Volumen del auto --> Discreto / Continuo si lo consideramos que es una funcion matematica y varia en un rango
#Eco rating --> Discreto / Ordinal si lo consideramos como una calificacion
print(datos.shape)
datos = datos.dropna()
print(datos.shape)

numerical_data = datos.select_dtypes(include=['number'])

correlation_matrix = numerical_data.corr()
print(correlation_matrix)

#Eliminamos atributos fuertemente relacionados 
#Positivos
# numerical_data.drop('curb-weight',axis=1,inplace=True)
# numerical_data.drop('engine-size',axis=1,inplace=True)

#Negativos
# numerical_data.drop('highway-mpg',axis=1,inplace=True)
# numerical_data.drop('horsepower',axis=1,inplace=True)

#Para el cuestionario
numerical_data.drop('horsepower',axis=1,inplace=True)
numerical_data.drop('city-mpg',axis=1,inplace=True)
numerical_data.drop('price',axis=1,inplace=True)


FileNotFoundError: [Errno 2] No such file or directory: '../../Lentes.csv'

In [9]:
#Seleccion de datos
X = np.array(numerical_data.iloc[:,:-1])
T = np.array(numerical_data['eco-rating'])
media_eco_rating = T.mean()

T = np.array(T > media_eco_rating) * 1

print(X)


[[2.54800000e+03 1.30000000e+02 2.70000000e+01 5.28019904e+05]
 [2.54800000e+03 1.30000000e+02 2.70000000e+01 5.28019904e+05]
 [2.82300000e+03 1.52000000e+02 2.60000000e+01 5.87592640e+05]
 [2.33700000e+03 1.09000000e+02 3.00000000e+01 6.34816956e+05]
 [2.82400000e+03 1.36000000e+02 2.20000000e+01 6.36734832e+05]
 [2.50700000e+03 1.36000000e+02 2.50000000e+01 6.24189969e+05]
 [2.84400000e+03 1.36000000e+02 2.50000000e+01 7.66364046e+05]
 [2.95400000e+03 1.36000000e+02 2.50000000e+01 7.66364046e+05]
 [3.08600000e+03 1.31000000e+02 2.00000000e+01 7.69115802e+05]
 [2.39500000e+03 1.08000000e+02 2.90000000e+01 6.22095552e+05]
 [2.39500000e+03 1.08000000e+02 2.90000000e+01 6.22095552e+05]
 [2.71000000e+03 1.64000000e+02 2.80000000e+01 6.22095552e+05]
 [2.76500000e+03 1.64000000e+02 2.80000000e+01 6.22095552e+05]
 [3.05500000e+03 1.64000000e+02 2.50000000e+01 7.04276370e+05]
 [3.23000000e+03 2.09000000e+02 2.20000000e+01 7.04276370e+05]
 [3.38000000e+03 2.09000000e+02 2.20000000e+01 7.066393

In [10]:
#Normalizado con standard
normalizador= preprocessing.StandardScaler()
X= normalizador.fit_transform(X)

In [111]:
#Normalizado con 0 to 1 
normalizador= preprocessing.MinMaxScaler()
X= normalizador.fit_transform(X)

In [11]:
ppn = Perceptron(alpha=0.05, n_iter=100, draw=0, random_state=None)
ppn.fit(X,T)

In [12]:
Y = ppn.predict(X)
aciertos = metrics.accuracy_score(Y,T)
print("%% accuracy = %.3f" % (aciertos * 100))

#Sin normalizar -> aprox 50% de aciertosr
#Normalizando -> 100% de aciertos

#Cuando eliminamos atributos fuertemente relacionados cercanos a 1 disminuye la efectividad en un 4%
#Cuando eliminamos cercanos a -1, la efectividad disminuye entre un 6 y un 10% en algunos casos

% accuracy = 100.000
