In [3]:
import numpy as np


In [65]:
a = np.array([1,2,3])
b = np.empty((2,3))
c = np.full((2,3),7)
d = np.zeros((2,3))
e = np.array([1,2,3,4,5,6,7,8])
e.reshape(-1,4)
f = np.ones((5,3))
g = np.identity(6)
r = range(5)
print(r)
h = np.random.choice(r, size=(2,3))



range(0, 5)


In [67]:
print(f.shape,len(f),f.ndim,f.size)

(5, 3) 5 2 15


In [74]:
array = np.array([[2,2,2],[1,2,3]])

# Suma de todos los elementos
total_sum = np.sum(array)
print("Suma total:", total_sum)

# Suma a lo largo de las filas (eje 1)
row_sum = np.sum(array, axis=1)
print("Suma por filas:", row_sum)

# Suma a lo largo de las columnas (eje 0)
col_sum = np.sum(array, axis=0)
print("Suma por columnas:", col_sum)

min_val = np.min(array)
print("Valor mínimo:", min_val)

# Mínimo por filas
row_min = np.min(array, axis=1)
print("Mínimo por filas:", row_min)

# Mínimo por columnas
col_min = np.min(array, axis=0)
print("Mínimo por columnas:", col_min)

max_val = np.max(array)
print("Valor máximo:", max_val)

# Máximo por filas
row_max = np.max(array, axis=1)
print("Máximo por filas:", row_max)

# Máximo por columnas
col_max = np.max(array, axis=0)
print("Máximo por columnas:", col_max)

Suma total: 12
Suma por filas: [6 6]
Suma por columnas: [3 4 5]
Valor mínimo: 1
Mínimo por filas: [2 1]
Mínimo por columnas: [1 2 2]
Valor máximo: 3
Máximo por filas: [2 3]
Máximo por columnas: [2 2 3]


: 

In [ ]:
# Manipulación de elementos en arrays
array = np.array([1, 2, 3])

# Append
array_appended = np.append(array, [4, 5, 6])
print("Array después de append:", array_appended)

# Insert
array_inserted = np.insert(array, 1, [9, 8])
print("Array después de insert:", array_inserted)

# Delete
array_deleted = np.delete(array, 1)
print("Array después de delete:", array_deleted)

# Reshape
array_reshaped = np.reshape(np.arange(6), (2, 3))
print("Array después de reshape:\n", array_reshaped)

# Ravel
array_raveled = np.ravel(array_reshaped)
print("Array después de ravel:", array_raveled)

# Flip
array_flipped = np.flip(array_reshaped, axis=1)
print("Array después de flip:\n", array_flipped)

# Manipulación de arrays entre sí
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# vstack
array_vstack = np.vstack((array1, array2))
print("Array después de vstack:\n", array_vstack)

# hstack
array_hstack = np.hstack((array1, array2))
print("Array después de hstack:", array_hstack)

# Concatenate
array3 = np.array([[7, 8, 9]])
array_concatenated = np.concatenate((array_vstack, array3), axis=0)
print("Array después de concatenate:\n", array_concatenated)

# Split
array_split = np.split(array_concatenated, 3)
print("Array después de split:", array_split)

# Tile
array_tiled = np.tile(array1, (2, 2))
print("Array después de tile:\n", array_tiled)

# Repeat
array_repeated = np.repeat(array1, 3)
print("Array después de repeat:", array_repeated)

In [11]:
import tensorflow as tf
print("¿TensorFlow está usando la GPU?:", tf.config.list_physical_devices('GPU'))
# Crear tensores
tensor_a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
tensor_b = tf.random.normal((2, 2), mean=0.0, stddev=1.0)

print("Tensor A:\n", tensor_a)
print("\nTensor B (aleatorio):\n", tensor_b)

# Operaciones matemáticas
tensor_sum = tf.add(tensor_a, tensor_b)
print("\nSuma de tensores:\n", tensor_sum)

tensor_matmul = tf.matmul(tensor_a, tensor_b)
print("\nMultiplicación matricial:\n", tensor_matmul)

# Manipulación de tensores
tensor_reshaped = tf.reshape(tensor_matmul, (1, 4))
print("\nTensor reordenado (reshape):\n", tensor_reshaped)

tensor_expanded = tf.expand_dims(tensor_reshaped, axis=-1)
print("\nTensor con dimensión añadida (expand_dims):\n", tensor_expanded)

tensor_squeezed = tf.squeeze(tensor_expanded)
print("\nTensor después de eliminar dimensiones de tamaño 1 (squeeze):\n", tensor_squeezed)

¿TensorFlow está usando la GPU?: []
Tensor A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Tensor B (aleatorio):
 tf.Tensor(
[[-1.3492662  -0.86581093]
 [ 0.1625013   0.461349  ]], shape=(2, 2), dtype=float32)

Suma de tensores:
 tf.Tensor(
[[-0.34926617  1.1341891 ]
 [ 3.1625013   4.461349  ]], shape=(2, 2), dtype=float32)

Multiplicación matricial:
 tf.Tensor(
[[-1.0242636   0.05688709]
 [-3.3977933  -0.7520368 ]], shape=(2, 2), dtype=float32)

Tensor reordenado (reshape):
 tf.Tensor([[-1.0242636   0.05688709 -3.3977933  -0.7520368 ]], shape=(1, 4), dtype=float32)

Tensor con dimensión añadida (expand_dims):
 tf.Tensor(
[[[-1.0242636 ]
  [ 0.05688709]
  [-3.3977933 ]
  [-0.7520368 ]]], shape=(1, 4, 1), dtype=float32)

Tensor después de eliminar dimensiones de tamaño 1 (squeeze):
 tf.Tensor([-1.0242636   0.05688709 -3.3977933  -0.7520368 ], shape=(4,), dtype=float32)


In [44]:
import pandas as pd

data = [
    ['Juan',20,'Argentina'],
    ['Maria',26,'Peru'],
    ['Pedro',18,'Brasil'],
    ['Jose',22,'Chile']
]

#forma 1
df = pd.DataFrame(data,columns=['Nombre','Edad','Pais'])
nuevo_user = ['Facundo',20,'Argentina']
df.loc[4] = nuevo_user
#forma 2
new_row = pd.DataFrame({'Nombre': ['Pedro'], 'Edad': [26], 'Pais': ['Colombia']})
nuevo_df = pd.concat([df,new_row], ignore_index=True)
nuevo_df.loc[6] = ['Mateo',21,'Peru']
#------------#
print(nuevo_df)
tabla_sin_pedro = nuevo_df.drop_duplicates(subset=['Nombre'], keep='first')
print('_--------------------_')
print(tabla_sin_pedro)
print('_--------------------_')
tabla_sin_pedro.loc[tabla_sin_pedro['Pais'] == 'Peru' , 'Pais'] = 'Perú'
print(tabla_sin_pedro)
#---------------#

# Guardar como archivo delimitado por tabuladores
tabla_sin_pedro.to_csv('data_tabulador.txt', sep='\t', index=False)

# Guardar como archivo delimitado por punto y coma
tabla_sin_pedro.to_csv('data_punto_y_coma.csv', sep=';', index=False)

# Guardar como archivo Excel
tabla_sin_pedro.to_excel('data_excel.xlsx', index=False)

# Guardar como archivo JSON
tabla_sin_pedro.to_json('data.json', orient='records', lines=True)

    Nombre  Edad       Pais
0     Juan    20  Argentina
1    Maria    26       Peru
2    Pedro    18     Brasil
3     Jose    22      Chile
4  Facundo    20  Argentina
5    Pedro    26   Colombia
6    Mateo    21       Peru
_--------------------_
    Nombre  Edad       Pais
0     Juan    20  Argentina
1    Maria    26       Peru
2    Pedro    18     Brasil
3     Jose    22      Chile
4  Facundo    20  Argentina
6    Mateo    21       Peru
_--------------------_
    Nombre  Edad       Pais
0     Juan    20  Argentina
1    Maria    26       Perú
2    Pedro    18     Brasil
3     Jose    22      Chile
4  Facundo    20  Argentina
6    Mateo    21       Perú
